---
repos:
  - repo: "https://github.com/astral-sh/ruff-pre-commit"
    rev: "v0.13.2"
    hooks:
      - id: "ruff-check"
        args: ["--fix"]
      - id: "ruff-format"
  - repo: "https://github.com/pre-commit/mirrors-mypy"
    rev: 'v1.18.2'
    hooks:
      - id: "mypy"
        args: ["--strict", "."]
        pass_filenames: false
        additional_dependencies:
          - "cinemagoerng==0.5.1"
          - "django-imdb==0.3.5"
          - "django-stubs[compatible-mypy]"
          - "enrich==1.2.7"
          - "nanodjango==0.12.2"
          - "parse-torrent-title==2.8.1"
          - "pocketsearch==0.41.0"
          - "rich-argparse==1.7.1"
...
